target:
- user_of_latest_model
continuous_cols:
- age_of_customer
- swimming_hours_per_week
- biking_hours_per_week
- running_hours_per_week
- total_training_hours_per_week
- vo2_max
- 10k_running_time_prediction
- calories_burned_per_week
- support_cases_of_customer
- customer_years
- most_current_software_update
categorical_cols:
- _cat_Male
- _cat_Other
- _cat_Germany
- _cat_Germayn
- _cat_India
- _cat_UK
- _cat_USA
- _cat_UnknownLand
- _cat_Berlin
- _cat_Birmingham
- _cat_Brisbane
- _cat_Chicago
- _cat_Delhi
- _cat_Hamburg
- _cat_London
- _cat_Los Angeles
- _cat_Manchester
- _cat_Melbourne
- _cat_Mumbai
- _cat_Munich
- _cat_New York
- _cat_Sydney
- _cat_Fitness
- _cat_Recreation
- _cat_Evening
- _cat_Morning
- _cat_Free
- _cat_Premium
- _cat_White
- _cat_Yes
date_columns: []
encode_date_columns: true
validation_split: 0.2
continuous_feature_transform: null
normalize_continuous_features: true
quantile_noise: 0
num_workers: 0
pin_memory: true
handle_unknown_categories: true
handle_missing_values: true
dataloader_kwargs: {}
task: classification
head: LinearHead
head_config:
  layers: ''
  activation: ReLU
  dropout: 0.05
  use_batch_norm: false
  initialization: kaiming
embedding_dims: null
embedding_dropout: 0.0
batch_norm_continuous_input: true
learning_rate: 0.0033134315698496015
loss: CrossEntropyLoss
metrics:
- accuracy
metrics_prob_input:
- false
metrics_params:
- {}
target_range: null
virtual_batch_size: null
seed: 42
_module_src: models.ft_transformer
_model_name: FTTransformerModel
_backbone_name: FTTransformerBackbone
_config_name: FTTransformerConfig
input_embed_dim: 32
embedding_initialization: kaiming_uniform
embedding_bias: true
share_embedding: false
share_embedding_strategy: fraction
shared_embedding_fraction: 0.25
attn_feature_importance: true
num_heads: 8
num_attn_blocks: 4
transformer_head_dim: null
attn_dropout: 0.1
add_norm_dropout: 0.1
ff_dropout: 0.1
ff_hidden_multiplier: 4
transformer_activation: GEGLU
batch_size: 64
data_aware_init_batch_size: 2000
fast_dev_run: false
max_epochs: 30
min_epochs: 1
max_time: null
accelerator: mps
devices: -1
devices_list: null
accumulate_grad_batches: 1
auto_lr_find: false
auto_select_gpus: true
check_val_every_n_epoch: 1
gradient_clip_val: 0.0
overfit_batches: 0.0
deterministic: false
profiler: null
early_stopping: valid_loss
early_stopping_min_delta: 0.001
early_stopping_mode: min
early_stopping_patience: 5
early_stopping_kwargs: {}
checkpoints: valid_loss
checkpoints_path: saved_models
checkpoints_every_n_epochs: 1
checkpoints_name: null
checkpoints_mode: min
checkpoints_save_top_k: 1
checkpoints_kwargs: {}
load_best: true
track_grad_norm: -1
progress_bar: rich
precision: 32
trainer_kwargs: {}
optimizer: AdamW
optimizer_params: {}
lr_scheduler: null
lr_scheduler_params: {}
lr_scheduler_monitor_metric: valid_loss
categorical_dim: 30
enable_checkpointing: true
